# export GIT_COMMIT_SHA_SHORT=`git rev-parse --short HEAD`
# export GIT_COMMIT_SHA=`git rev-parse --verify HEAD`
baseurl = "https://saleh.soy"
DefaultContentLanguage = "en"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  tabTitle = "qloƃ~"
  logo = "moi.jpg"
  favicon = "alien_blue.ico"
  dateFormat = "2, January 2006"
  mainSections = ["post","posts"]

  commit = "https://gitlab.com/qirh/blog/tree/"
  rss = true
  wordCount = true

  useHLJS = false   #ummm what is this?
  author = false
  comments = false
  readingTime = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false
  lastModified = false
  selfHosted = false

[permalinks]
  post = "/:title"

[markup.goldmark.renderer]
  unsafe= true

[Author]
  name = "Saleh"
  email = "saleh@alghusson.com"
  gitlab = "qirh"
  github = "qirh"

[[menu.main]]
    name = "About"
    url = "about"
    weight = 2
