#!/bin/sh
set -eu

ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
APP=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

ROOT="$ROOT" APP="$APP" node <<'NODE'
const fs = require('fs');
const path = require('path');

const root = process.env.ROOT;
const app = process.env.APP;
const postsDir = path.join(root, 'posts');
const pagesDir = path.join(root, 'pages');
const routesDir = path.join(app, 'src', 'routes');
const libDir = path.join(app, 'src', 'lib');

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function removeGeneratedRoutes(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (!entry.isDirectory()) continue;
    const sentinel = path.join(fullPath, '.generated');
    if (fs.existsSync(sentinel)) {
      fs.rmSync(fullPath, { recursive: true, force: true });
    } else {
      removeGeneratedRoutes(fullPath);
    }
  }
}

function readMarkdown(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function parseFrontmatter(markdown) {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n?/);
  const metadata = {};
  if (!match) return { metadata, body: markdown };

  for (const line of match[1].split('\n')) {
    const field = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!field) continue;
    metadata[field[1]] = field[2].replace(/^["']|["']$/g, '');
  }

  return { metadata, body: markdown.slice(match[0].length) };
}

function plainExcerpt(markdown) {
  const firstParagraph = markdown
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.trim())
    .find(Boolean) || '';

  return firstParagraph
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/<[^>]*>/g, ' ')
    .replace(/[`*_#>]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 280);
}

function markdownForSvelte(markdown) {
  return markdown
    .replace(/<(?=[^A-Za-z/!?])/g, '&lt;')
    .replace(/<img\b(?![^>]*\balt=)([^>]*)>/g, '<img$1 alt="">');
}

function markdownFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((file) => file.endsWith('.md'))
    .sort();
}

function titleFromSlug(slug) {
  return slug
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function writeGeneratedRoute(slug, sourcePath) {
  const routeDir = path.join(routesDir, slug);
  ensureDir(routeDir);
  fs.writeFileSync(path.join(routeDir, '+page.svx'), markdownForSvelte(readMarkdown(sourcePath)));
  fs.writeFileSync(path.join(routeDir, '.generated'), 'generated by scripts/sync-posts.sh\n');
}

ensureDir(routesDir);
ensureDir(libDir);
removeGeneratedRoutes(routesDir);

const posts = markdownFiles(postsDir).map((file) => {
  const slug = path.basename(file, '.md');
  const sourcePath = path.join(postsDir, file);
  const markdown = readMarkdown(sourcePath);
  const { metadata, body } = parseFrontmatter(markdown);

  if (!metadata.title || !metadata.date) {
    throw new Error(`${sourcePath} must define title and date frontmatter`);
  }

  writeGeneratedRoute(slug, sourcePath);
  return {
    slug,
    title: metadata.title,
    date: metadata.date,
    excerpt: plainExcerpt(body)
  };
});

const pages = markdownFiles(pagesDir).map((file) => {
  const slug = path.basename(file, '.md');
  const sourcePath = path.join(pagesDir, file);
  const { metadata } = parseFrontmatter(readMarkdown(sourcePath));

  writeGeneratedRoute(slug, sourcePath);
  return {
    slug,
    title: metadata.title || titleFromSlug(slug)
  };
});

posts.sort((a, b) => b.date.localeCompare(a.date));
pages.sort((a, b) => a.slug.localeCompare(b.slug));
fs.writeFileSync(path.join(libDir, 'pages-manifest.json'), `${JSON.stringify(pages, null, 2)}\n`);
fs.writeFileSync(path.join(libDir, 'posts-manifest.json'), `${JSON.stringify(posts, null, 2)}\n`);
NODE
